### ISSUE TITLE
Can't install via composer

### ISSUE THREAD

**Issue by rtd62** [reliqarts/mardin#3]
I tried to install your package via composer, but Terminal threw this error at me:
```[InvalidArgumentException]                                                     
  Could not find package reliqarts/mardin at any version for your minimum-stabi  
  lity (stable). Check the package spelling or your minimum-stability```

**Comment by reliq** [comment]
Ah, thanks for reporting this @rtd62!

This is because there is no "stable" release for mardin yet. A stable release should be forthcoming soon. In the meantime you may update your `minimum-stability` to `beta` or `dev` and it should install. 

In addition use `"prefer-stable": true` to tell composer to prefer more stable packages over unstable ones when finding compatible stable packages is possible.

e.g.
```js
{
// ...
    "prefer-stable": true,
    "minimum-stability": "dev"
// ...
}
```
---
Reference: 
- https://getcomposer.org/doc/04-schema.md#minimum-stability
- https://getcomposer.org/doc/04-schema.md#prefer-stable



Cheers :beers:

**Comment by rtd62** [comment]
Thanks!! I got it to install by typing this:
`php composer.phar require reliqarts/mardin:dev-master --prefer-stable`

I'm going to have some fun now! 🍻
